language: cpp
before_script:
  - pip install --user codecov
script:
  - ./autogen.sh --enable-coverage && make all test
  - (cd src/lib/ebus/test && ./test_symbol && ./test_filereader && ./test_data && ./test_message)
  - ./src/ebusd/ebusd --help
after_success:
  - find src/ebusd -name "*.gc*"
  - g++ --version
  - gcov --version
  - hexdump -C src/lib/ebus/symbol.gcno |head
  - hexdump -C src/lib/ebus/symbol.gcda |head
  - gcov -pb ./src/ebusd/symbol.gcno
  - codecov
