name: Build

on:
  push:
    branches: [ dockerbuildtest ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure and build
      run: ./make_debian.sh
