name: Build

on:
  push:
    branches: [ ignore ]
    paths:
      - 'src/**'
      - 'autogen.sh'
      - 'config*'
      - 'Makefile*'
      - 'make_debian.sh'
      - 'contrib/docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build
        run: cd contrib/docker && ./build.sh
